In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('dataset.csv')
df.head()

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 114000 entries, 0 to 113999
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        114000 non-null  int64
 1   track_id          114000 non-null  str
 2   artists           113999 non-null  str
 3   album_name        113999 non-null  str
 4   track_name        113999 non-null  str
 5   popularity        114000 non-null  int64
 6   duration_ms       114000 non-null  int64
 7   explicit          114000 non-null  bool
 8   danceability      114000 non-null  float64
 9   energy            114000 non-null  float64
 10  key               114000 non-null  int64
 11  loudness          114000 non-null  float64
 12  mode              114000 non-null  int64
 13  speechiness       114000 non-null  float64
 14  acousticness      114000 non-null  float64
 15  instrumentalness  114000 non-null  float64
 16  liveness          114000 non-null  float64
 17  valence           114000 non-null  float64
 18  tempo             114000 non-null  float64
 19  time_signature    114000 non-null  int64
 20  track_genre       114000 non-null  str
dtypes: bool(1), float64(9), int64(6), str(5)
memory usage: 17.5 MB

**Realizando uma limpeza no dataset**

Retirando a coluna Unnamed: 0

In [4]:
df = df.drop(columns=["Unnamed: 0"])

Verificando linhas que possuem colunas com valores nulos

In [5]:
df.isnull().sum()

track_id            0
artists             1
album_name          1
track_name          1
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

Realizando um drop nas linhas encontradas

In [6]:
df = df.dropna()

Verificação final

In [7]:
df.isnull().sum()

track_id            0
artists             0
album_name          0
track_name          0
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

**Filtrando valores duplicados**

Somando a quantidade de linhas duplicadas

In [8]:
print('Total de linhas duplicadas:', df.duplicated().sum())

Total de linhas duplicadas: 450

Somando a quantidade de linhas com o ID duplicado

In [9]:
print('Total de IDs duplicados:', df.duplicated(subset='track_id').sum())

Total de IDs duplicados: 24259

Realizando um drop de todas as linhas duplicadas, deixando apenas aqueles com a maior popularidade

In [10]:
df = df.sort_values('popularity', ascending=False)
df = df.drop_duplicates(subset='track_id')

Verificação final

In [11]:
print('Total de linhas duplicadas:', df.duplicated().sum())
print('Total de IDs duplicados:', df.duplicated(subset='track_id').sum())

Total de linhas duplicadas: 0
Total de IDs duplicados: 0

In [12]:
df['popularity'].describe()

count    89740.000000
mean        33.207566
std         20.574086
min          0.000000
25%         19.000000
50%         33.000000
75%         49.000000
max        100.000000
Name: popularity, dtype: float64

**Primeira etapa: top 10 gêneros mais populares do Spotify**

Agrupando os gêneros por média de popularidade

In [13]:
genre_popularity_mean = df.groupby('track_genre', as_index=False)['popularity'].mean().sort_values('popularity', ascending=False).head(10)
genre_popularity_mean

    track_genre  popularity
65        k-pop   59.193925
71        metal   58.131313
81     pop-film   58.123905
15        chill   55.707895
94          sad   51.529948
33          emo   50.369478
44       grunge   50.022837
102  songwriter   49.245968
30          edm   49.236364
80          pop   49.140089

**Segunda etapa: top 10 artistas mais populares**

In [15]:
artists_popularity_mean = df.groupby('artists', as_index=False)['popularity'].mean().sort_values('popularity', ascending=False).head(10)
artists_popularity_mean

                          artists  popularity
24119        Sam Smith;Kim Petras       100.0
3629             Bizarrap;Quevedo        99.0
17442               Manuel Turizo        98.0
2857   Bad Bunny;Chencho Corleone        97.0
2855      Bad Bunny;Bomba Estéreo        95.0
13565                        Joji        94.0
3443                      Beyoncé        93.0
11491                Harry Styles        92.0
22845           Rema;Selena Gomez        92.0
16525                   Luar La L        91.0

Ao analisar a primeira amostra dos artistas mais populares, foi identificado um problema: algumas linhas possuem mais de um nome na coluna "artists", devido à presença de colaborações (feats).
Para tornar a análise mais precisa e justa, foi realizada uma transformação nos dados, separando os artistas em registros individuais.

In [16]:
df['artists'] = df['artists'].str.split(';')
df = df.explode('artists')
artists_popularity_mean = df.groupby('artists', as_index=False)['popularity'].mean().sort_values('popularity', ascending=False).head(10)
artists_popularity_mean

                artists  popularity
3234           Bizarrap        99.0
21043           Quevedo        99.0
10483      Harry Styles        92.0
15548         Luar La L        91.0
2766      Beach Weather        90.0
19886   Pablo Pesadilla        88.0
20701  Polimá Westcoast        88.0
19479    Olivia Rodrigo        87.4
28711        Yung Gravy        87.0
2465               BYOR        87.0